version: "3.8"
services:
  db:
    image: postgres:14
    container_name: flask_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: lab3_db
    ports:
      - "5432:5432"