services:
  - type: web
    name: lab3-flask
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash -c 'flask db upgrade && gunicorn app:app'"
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: DATABASE_URL
        fromDatabase:
          name: lab3-db
          property: connectionString

databases:
  - name: lab3-db